import tkinter as tk
from tkinter import simpledialog
from tkinter import *
from tkinter.ttk import *
from tkinter.tix import *
import tkinter.messagebox as msgbox
import customtkinter as ctk
from matplotlib import artist
import generators as gn
import xlfile as xl
import ai_project as ai